
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import *
import gui_text

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


# master = Tk()

# window.geometry("526x687")
# window.configure(bg = "#FFFFFF")

class Landing(Frame):
    def __init__(self, master): 
        Frame.__init__(self, master, width = 526, height = 687)
        self.canvas = Canvas(
            master,
            bg = "#FFFFFF",
            height = 687,
            width = 526,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)
        self.canvas.create_text(
            173.47903442382812,
            333.7021789550781,
            anchor="nw",
            text="Modern Ciphers",
            fill="#000000",
            font=("HKGrotesk BoldLegacy", 28 * -1)
        )

        self.canvas.create_text(
            115.84478759765625,
            384.4202880859375,
            anchor="nw",
            text="choose object to encrypt or decrypt",
            fill="#000000",
            font=("HKGrotesk BoldLegacy", 17 * -1)
        )

        self.image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        self.image_1 = self.canvas.create_image(
            262.29193115234375,
            181.2986602783203,
            image=self.image_image_1
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        self.button_1 = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: getMethod(variable.get()),
            relief="flat"
        )
        self.button_1.place(
            x=204.025146484375,
            y=504.8758239746094,
            width=118.72650146484375,
            height=37.462249755859375
        )
        options = ["File", "Text"]
        variable = StringVar(master)
        variable.set(options[0])

        methods = OptionMenu(master, variable, *options)
        methods.place(
            x=263,
            y=450,
            anchor=N
        )

        def getMethod(method):
            if (method == "File"):
                pass
            elif (method == "Text"):
                self.master.switch_frame(gui_text.vigenere_Extended)
